# Pytorch공식 홈페이지의 Pytorch로 딥러닝하기: 60분만에 끝장내기를 리뷰
* https://tutorials.pytorch.kr/beginner/deep_learning_60min_blitz.html

In [56]:
import torch
import numpy as np

## 1.tensor 초기화

In [83]:
# list to tensor
data = [[1, 2], [3, 4]]
a = torch.tensor(data)
c = torch.Tensor(data)  # 이것도 가능
b = torch.FloatTensor(data)
a, b, c

(tensor([[1, 2],
         [3, 4]]),
 tensor([[1., 2.],
         [3., 4.]]),
 tensor([[1., 2.],
         [3., 4.]]))

In [58]:
# np.array to tensor
np_data = np.array(data)
c = torch.tensor(np_data)
d = torch.from_numpy(np_data)  # 왜 이걸 굳이 써야 하는지는 모르겠음
c, d

(tensor([[1, 2],
         [3, 4]]),
 tensor([[1, 2],
         [3, 4]]))

### 같은 shape의 tensor 생성하기: ***_like()
* 주의 : 인자는 tensor여야만 한다.

In [59]:
x_ones = torch.ones_like(a)
# x_ones2 = torch.ones_like(data) #!! Error!! input must be Tensor!
x_rand = torch.rand_like(a, dtype=torch.float) # dtype꼭 명시!
x_ones, x_rand

(tensor([[1, 1],
         [1, 1]]),
 tensor([[0.0235, 0.4665],
         [0.8580, 0.4555]]))

### 무작위 또는 상수 값 생성
* rand()
* ones()
* zeros()

In [60]:
shape = (2, 3)
rand_ts = torch.rand(shape)
ones_ts = torch.ones(shape)
zeros_ts = torch.zeros(shape)

rand_ts, ones_ts, zeros_ts

(tensor([[0.6365, 0.1627, 0.8834],
         [0.2397, 0.2366, 0.5025]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

### 텐서의 속성(attribute) 확인
shape, dtype, device(어느 장치에 저장되는지!) 확인

In [61]:
ts = torch.rand(3, 4)
ts.shape, ts.dtype, ts.device

(torch.Size([3, 4]), torch.float32, device(type='cpu'))

In [62]:
# 참고 size()도 shape과 같음
ts.size()

torch.Size([3, 4])

## 2. 텐서 연산
* [상세 연산]() : transpose, indexing, slicing, 수학, 선형대수, random sampling 등등 확인
* GPU할당시 CPU보다 더 빠르게 연산 실행 가능

In [63]:
if torch.cuda.is_available():
    ts = ts.to('cuda:6')
    print(f'tessor는 { ts.device }에 저장됩니다.')
ts

tessor는 cuda:6에 저장됩니다.


tensor([[0.2271, 0.9452, 0.8613, 0.9989],
        [0.8273, 0.2053, 0.2999, 0.2290],
        [0.9542, 0.5131, 0.3664, 0.9354]], device='cuda:6')

보통은 이렇게 쓴다.

In [64]:
device = torch.device(f'cuda:6' if torch.cuda.is_available else 'cpu')
ts = ts.to(device)
ts

tensor([[0.2271, 0.9452, 0.8613, 0.9989],
        [0.8273, 0.2053, 0.2999, 0.2290],
        [0.9542, 0.5131, 0.3664, 0.9354]], device='cuda:6')

### 표준 인덱싱 및 슬라이싱
* numpy랑 똑!같다.

In [65]:
# 표준 인덱싱 및 슬라이싱
ts = torch.ones(4, 4)
ts[:, 1] = 0
ts

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

### 텐서 합치기

In [66]:
# dim 0은 행기준 합치기, 1은 열기준 합치기
t1 = torch.cat([ts, ts, ts], dim=1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

### 곱셈, 행렬 곱셈

In [67]:
# 곱셈(element-wise)
result = ts.mul(ts)
result2 = ts*ts
result, result2

(tensor([[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]),
 tensor([[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]))

In [68]:
# 행렬 곱
result = ts.matmul(ts.T)
result2 = ts @ ts.T     # !!! 특이하다. 첨알았다.
result, result2

(tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]),
 tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]))

### in-place 연산
접미어 'xx_'를 갖는 연산들이 해당됨. 메모리 효율은 있을지언정 오류가능성 때문에 torch에서 권장하진 않는다.

In [73]:
ts2 = torch.ones_like(ts).copy_(ts)  # tensor 복사 방법임. 일반적 np의 copy()론 못함.
ts2.add_(ts2)
result = ts + ts
ts2, result

(tensor([[2., 0., 2., 2.],
         [2., 0., 2., 2.],
         [2., 0., 2., 2.],
         [2., 0., 2., 2.]]),
 tensor([[2., 0., 2., 2.],
         [2., 0., 2., 2.],
         [2., 0., 2., 2.],
         [2., 0., 2., 2.]]))

## 3. Numpy 변환(Bridge)
!! cpu상의 tensor와 numpy 배열은 메모리를 공유하게 되므로 하나를 변경하면 다른 하나도 변경.(마치 포인터)

???!!! 근데 실제로 해보니 변경 안됨.

### 텐서 to numpy

In [79]:
t = torch.ones(5)
n = t.numpy()
t, n

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

In [87]:
# 값을 공유한다는데 공유 안하네??!
t = t + 1
t, n

(tensor([3, 4, 5, 6, 7]), array([3, 4, 5, 6, 7]))

In [81]:
t.add_(1)
t, n

(tensor([3., 3., 3., 3., 3.]), array([1., 1., 1., 1., 1.], dtype=float32))

In [89]:
# numpy로 해도 공유 안함.
n = np.array([1,2,3,4,5])
t = torch.Tensor(n)

n = n + 1
n, t

(array([2, 3, 4, 5, 6]), tensor([1., 2., 3., 4., 5.]))